name: build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: startup docker
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
        sudo rm -rf /Library/Frameworks/Python.framework/
        brew update          
        brew install qemu
        brew install docker
        brew install colima
        uname -rsm
        sw_vers
        which limactl
        file $(which limactl)
        sysctl sysctl.proc_translated
        # cp -f ./limactl /opt/homebrew/Cellar/lima/0.22.0/bin/limactl
        # sudo curl -L -o /opt/homebrew/Cellar/lima/0.22.0/bin/limactl https://github.com/mikekazakov/lima-nohvf/raw/master/limactl
        # sudo chmod +x /opt/homebrew/Cellar/lima/0.22.0/bin/limactl
        LIMACTL_PATH=$(brew --prefix)/bin/limactl
        sudo curl -L -o $LIMACTL_PATH https://github.com/mikekazakov/lima-nohvf/raw/master/limactl && sudo chmod +x $LIMACTL_PATH
        colima start --network-address --arch arm64 --vm-type=qemu
    - name: startup docker containers
      run: |
        ./start.sh
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: colima-logs
        path: /Users/runner/.colima/_lima/colima/*.log

#         brew unlink colima
#         curl -L -o /usr/local/bin/colima https://github.com/abiosoft/colima/releases/download/v0.5.6/colima-Darwin-x86_64 && sudo chmod +x /usr/local/bin/colima
