name: build
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-14
    steps:
    - name: Install deps
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
        sudo rm -rf /Library/Frameworks/Python.framework/
        brew update
        brew install docker
        brew install qemu
        brew install colima
#        brew unlink colima
#        curl -L -o /usr/local/bin/colima https://github.com/abiosoft/colima/releases/download/v0.5.6/colima-Darwin-x86_64 && sudo chmod +x /usr/local/bin/colima
        colima start --network-address --arch arm64 --vm-type=qemu
